name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
  
permissions:
  contents: read


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: SetLocale
      run: |
        sudo locale-gen ja_JP.UTF-8
        sudo update-locale LANG=ja_JP.UTF-8
    - name: Up container
      run: docker compose up -d
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'